import { Geist, Geist_Mono } from "next/font/google";
import { CarProvider } from "@/contextApi/CarContext";
import Footer from "@/components/layout/Footer";
import Loader from "@/components/miniWidgets/Loader";
import ProgressBarProviders from "@/components/miniWidgets/Progressbar";
import NEXT_PUBLIC_API_URL from "@/components/layout/Url";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Rental App",
  description: "Generated by create next app",
};

// const NEXT_PUBLIC_BASE_URL = "https://car-rent-appl.netlify.app/";

const fetchData = async () => {
  try {
    console.log("url", NEXT_PUBLIC_API_URL);

    const eventResponse = await fetch(
      `${NEXT_PUBLIC_API_URL}/data/inventory.json`
    );
    const inventoryData = await eventResponse.json();
    // console.log("inventoryData in layout", inventoryData);

    return { inventoryData };
  } catch (error) {
    console.error("Error fetching data:", error);
    return { inventoryData: null };
  }
};
export default async function RootLayout({ children }) {
  const { inventoryData } = await fetchData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Loader />
        <CarProvider inventoryData={inventoryData}>
          <ProgressBarProviders>
            {/* <Navbar /> */}
            {children}
            <Footer />
          </ProgressBarProviders>
        </CarProvider>
      </body>
    </html>
  );
}
